const mongoose = require('mongoose');
const Spacefarer = require('../models/SpacefarerSchema');
require('dotenv').config();

mongoose.connect(process.env.MONGO_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const spacefarers = [
  {
    name: 'Zylo Korr',
    stardustCollection: 1500,
    wormholeSkill: 85,
    originPlanet: 'Xenon Prime',
    spacesuitColor: 'Silver',
    department: 'Exploration',
    position: 'Commander',
  },
  {
    name: 'Liora Vex',
    stardustCollection: 2300,
    wormholeSkill: 95,
    originPlanet: 'Nebulon V',
    spacesuitColor: 'Gold',
    department: 'Science',
    position: 'Astrobiologist',
  },
  {
    name: 'Drax Thal',
    stardustCollection: 800,
    wormholeSkill: 70,
    originPlanet: 'Andromeda-7',
    spacesuitColor: 'Black',
    department: 'Security',
    position: 'Guardian',
  },
  {
    name: "Seren Q'tar",
    stardustCollection: 1200,
    wormholeSkill: 78,
    originPlanet: 'Epsilon Eridani',
    spacesuitColor: 'Blue',
    department: 'Engineering',
    position: 'Systems Engineer',
  },
  {
    name: 'Kaela Voss',
    stardustCollection: 1750,
    wormholeSkill: 82,
    originPlanet: 'Tau Ceti IV',
    spacesuitColor: 'Red',
    department: 'Medical',
    position: 'Xenobiologist',
  },
  {
    name: 'Tarn Xeth',
    stardustCollection: 2600,
    wormholeSkill: 98,
    originPlanet: 'Vega Prime',
    spacesuitColor: 'Green',
    department: 'Command',
    position: 'Fleet Admiral',
  },
  {
    name: 'Orin Dax',
    stardustCollection: 500,
    wormholeSkill: 65,
    originPlanet: 'Proxima Centauri B',
    spacesuitColor: 'Orange',
    department: 'Mining',
    position: 'Resource Specialist',
  },
  {
    name: 'Nyssa Ro',
    stardustCollection: 3200,
    wormholeSkill: 88,
    originPlanet: 'Rigel IX',
    spacesuitColor: 'White',
    department: 'Diplomacy',
    position: 'Ambassador',
  },
  {
    name: 'Vael Syn',
    stardustCollection: 1400,
    wormholeSkill: 76,
    originPlanet: 'Sirius A-2',
    spacesuitColor: 'Teal',
    department: 'Logistics',
    position: 'Navigation Officer',
  },
  {
    name: 'Juno Ral',
    stardustCollection: 900,
    wormholeSkill: 72,
    originPlanet: 'Kepler-442b',
    spacesuitColor: 'Purple',
    department: 'Science',
    position: 'Exobotanist',
  },
  {
    name: 'Marek Sol',
    stardustCollection: 3000,
    wormholeSkill: 94,
    originPlanet: 'Alpha Centauri A',
    spacesuitColor: 'Black',
    department: 'Command',
    position: 'Captain',
  },
  {
    name: 'Lyra Vonn',
    stardustCollection: 2100,
    wormholeSkill: 80,
    originPlanet: 'Gliese 581g',
    spacesuitColor: 'Silver',
    department: 'Engineering',
    position: 'Quantum Technician',
  },
  {
    name: 'Toren Xe',
    stardustCollection: 1100,
    wormholeSkill: 68,
    originPlanet: 'Barnard’s Star',
    spacesuitColor: 'Blue',
    department: 'Security',
    position: 'Weapons Specialist',
  },
  {
    name: 'Cassia Nox',
    stardustCollection: 2800,
    wormholeSkill: 97,
    originPlanet: 'Zeta Reticuli',
    spacesuitColor: 'Gold',
    department: 'Exploration',
    position: 'Star Cartographer',
  },
  {
    name: 'Elias Vex',
    stardustCollection: 950,
    wormholeSkill: 74,
    originPlanet: 'Epsilon Indi',
    spacesuitColor: 'Green',
    department: 'Medical',
    position: 'Cybernetic Surgeon',
  },
  {
    name: 'Nova Thorne',
    stardustCollection: 5000,
    wormholeSkill: 100,
    originPlanet: 'Trappist-1d',
    spacesuitColor: 'Red',
    department: 'Command',
    position: 'Supreme Admiral',
  },
  {
    name: 'Orion Zeph',
    stardustCollection: 1950,
    wormholeSkill: 81,
    originPlanet: 'Upsilon Andromedae',
    spacesuitColor: 'Purple',
    department: 'Diplomacy',
    position: 'Intergalactic Liaison',
  },
  {
    name: 'Saria Vel',
    stardustCollection: 1700,
    wormholeSkill: 79,
    originPlanet: 'Lalande 21185',
    spacesuitColor: 'White',
    department: 'Logistics',
    position: 'Supply Chain Coordinator',
  },
  {
    name: 'Kirin Vox',
    stardustCollection: 2450,
    wormholeSkill: 92,
    originPlanet: 'Kapteyn’s Star',
    spacesuitColor: 'Orange',
    department: 'Engineering',
    position: 'AI Systems Engineer',
  },
  {
    name: 'Xan Dray',
    stardustCollection: 1350,
    wormholeSkill: 77,
    originPlanet: 'HD 40307g',
    spacesuitColor: 'Teal',
    department: 'Exploration',
    position: 'Xenoarcheologist',
  },
];

async function seedDB() {
  await Spacefarer.deleteMany({});
  await Spacefarer.insertMany(spacefarers);
  console.log('🌌 Sample spacefarers inserted!');
  mongoose.connection.close();
}

seedDB();
